import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Windows10
 */
public class Quebracbc extends javax.swing.JFrame {

    /**
     * Creates new form Quebracbc
     */
    public Quebracbc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        num10 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num12 = new javax.swing.JButton();
        num11 = new javax.swing.JButton();
        num13 = new javax.swing.JButton();
        num14 = new javax.swing.JButton();
        num15 = new javax.swing.JButton();
        vazio = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        embar = new javax.swing.JButton();
        solu = new javax.swing.JButton();
        clicks = new javax.swing.JPanel();
        clique = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0), 4));

        num1.setBackground(new java.awt.Color(0, 204, 0));
        num1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        num1.setText("1");
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });

        num2.setBackground(new java.awt.Color(0, 204, 0));
        num2.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        num2.setText("2");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });

        num3.setBackground(new java.awt.Color(0, 204, 0));
        num3.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        num3.setText("3");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });

        num4.setBackground(new java.awt.Color(0, 204, 0));
        num4.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        num4.setText("4");
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });

        num5.setBackground(new java.awt.Color(0, 204, 0));
        num5.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        num5.setText("5");
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });

        num6.setBackground(new java.awt.Color(0, 204, 0));
        num6.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        num6.setText("6");
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });

        num7.setBackground(new java.awt.Color(0, 204, 0));
        num7.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        num7.setText("7");
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });

        num9.setBackground(new java.awt.Color(0, 204, 0));
        num9.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        num9.setText("9");
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });

        num10.setBackground(new java.awt.Color(0, 204, 0));
        num10.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        num10.setText("10");
        num10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num10ActionPerformed(evt);
            }
        });

        num8.setBackground(new java.awt.Color(0, 204, 0));
        num8.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        num8.setText("8");
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });

        num12.setBackground(new java.awt.Color(0, 204, 0));
        num12.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        num12.setText("12");
        num12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num12ActionPerformed(evt);
            }
        });

        num11.setBackground(new java.awt.Color(0, 204, 0));
        num11.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        num11.setText("11");
        num11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num11ActionPerformed(evt);
            }
        });

        num13.setBackground(new java.awt.Color(0, 204, 0));
        num13.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        num13.setText("13");
        num13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num13ActionPerformed(evt);
            }
        });

        num14.setBackground(new java.awt.Color(0, 204, 0));
        num14.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        num14.setText("14");
        num14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num14ActionPerformed(evt);
            }
        });

        num15.setBackground(new java.awt.Color(0, 204, 0));
        num15.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        num15.setText("15");
        num15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num15ActionPerformed(evt);
            }
        });

        vazio.setBackground(new java.awt.Color(0, 204, 0));
        vazio.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        vazio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vazioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(num13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vazio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vazio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 370));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 4));

        embar.setBackground(new java.awt.Color(0, 204, 0));
        embar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        embar.setText("Embaralha");
        embar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                embarActionPerformed(evt);
            }
        });

        solu.setBackground(new java.awt.Color(0, 204, 0));
        solu.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        solu.setText("Solução");
        solu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soluActionPerformed(evt);
            }
        });

        clicks.setBackground(new java.awt.Color(0, 204, 0));

        clique.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        clique.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout clicksLayout = new javax.swing.GroupLayout(clicks);
        clicks.setLayout(clicksLayout);
        clicksLayout.setHorizontalGroup(
            clicksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clicksLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(clique, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        clicksLayout.setVerticalGroup(
            clicksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clicksLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(clique, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(embar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(solu, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(clicks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clicks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(embar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(solu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 420, 150));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int contador;
    
     void Troca(JButton Butt1, JButton Butt2){       
        String Numero = Butt2.getText();
        
        if (Numero == "")
        {
            Butt2.setText(Butt1.getText());
            Butt1.setText("");
        }
    }
    
    public void embaralhar(){      
        num1.setText("8");
        num2.setText("5");
        num3.setText("15");
        num4.setText("7");
        num5.setText("9");
        num6.setText("6");
        num7.setText("10");
        num8.setText("14");
        num9.setText("1");
        num10.setText("12");
        num11.setText("3");
        num12.setText("13");
        num13.setText("2");
        num14.setText("4");
        num15.setText("11");
        vazio.setText("");       
    }
    
    public void solucao(){      
        num1.setText("1");
        num2.setText("2");
        num3.setText("3");
        num4.setText("4");
        num5.setText("5");
        num6.setText("6");
        num7.setText("7");
        num8.setText("8");
        num9.setText("9");
        num10.setText("10");
        num11.setText("11");
        num12.setText("12");
        num13.setText("13");
        num14.setText("14");
        num15.setText("15");
        vazio.setText("");       
    }
    
    public void mensagem(){
        String botao1 = num1.getText();//acessor
        String botao2 = num2.getText();
        String botao3 = num3.getText();
        String botao4 = num4.getText();
        String botao5 = num5.getText();
        String botao6 = num6.getText();
        String botao7 = num7.getText();
        String botao8 = num8.getText();
        String botao9 = num9.getText();
        String botao10 = num10.getText();
        String botao11 = num11.getText();
        String botao12 = num12.getText();
        String botao13 = num13.getText();
        String botao14 = num14.getText();
        String botao15 = num15.getText();
        
        //Verifica atraves do metodo acessor na vareavel do botão, se o texto/numero contido no botão é a certa
        if(botao1 == "1" && botao2 == "2" && botao3 == "3" && botao4 == "4" && botao5 == "5" && botao6 == "6" && botao7 == "7" && botao8 == "8" && botao9 == "9" && botao10 == "10" &&
                botao11 == "11" && botao12 == "12" && botao13 == "13" && botao14 == "14" && botao15 == "15"){
            JOptionPane.showMessageDialog(null,"Voce ganhou","Quebra-cabeça",JOptionPane.INFORMATION_MESSAGE);
            //caso a sequencia esteja certa aparece uma mensagem q a pessoa ganhou
        }
        
        //a cada clique aparecera no label a contagem
        contador = contador + 1;
        clique.setText(Integer.toString(contador));
        
    }
       
    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        Troca(num1, num2);
        Troca(num1, num5);
         mensagem();       
    }//GEN-LAST:event_num1ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        Troca(num2, num1);
        Troca(num2, num3);
        Troca(num2, num6);
         mensagem();
        
    }//GEN-LAST:event_num2ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        Troca(num3, num2);
        Troca(num3, num4);
        Troca(num3, num7);
        mensagem();
    }//GEN-LAST:event_num3ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        Troca(num4, num3);
        Troca(num4 , num8);
        mensagem();
    }//GEN-LAST:event_num4ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        Troca(num5, num1);
        Troca(num5, num6);
        Troca(num5, num9);
        mensagem();
    }//GEN-LAST:event_num5ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        Troca(num6, num2);
        Troca(num6, num5);
        Troca(num6, num7);
        Troca(num6, num10);
        mensagem();
    }//GEN-LAST:event_num6ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        Troca(num7, num3);
        Troca(num7, num6);
        Troca(num7, num8);
        Troca(num7, num11);
        mensagem();
    }//GEN-LAST:event_num7ActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        Troca(num8, num4);
        Troca(num8, num7);
        Troca(num8, num12);
        mensagem();
    }//GEN-LAST:event_num8ActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        Troca(num9, num5);
        Troca(num9, num10);
         Troca(num9, num13);
         mensagem();

    }//GEN-LAST:event_num9ActionPerformed

    private void num10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num10ActionPerformed
        Troca(num10, num6);
        Troca(num10, num9);
        Troca(num10, num11);
        Troca(num10, num14);
        mensagem();
    }//GEN-LAST:event_num10ActionPerformed

    private void num11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num11ActionPerformed
        Troca(num11, num7);
        Troca(num11, num10);
        Troca(num11, num12);
        Troca(num11, num15);
        mensagem();
    }//GEN-LAST:event_num11ActionPerformed

    private void num12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num12ActionPerformed
       Troca(num12, num8);
       Troca(num12, num11);
       Troca(num12, vazio);
       mensagem();
    }//GEN-LAST:event_num12ActionPerformed

    private void num13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num13ActionPerformed
        Troca(num13, num9);
        Troca(num13, num14);
        mensagem();       
    }//GEN-LAST:event_num13ActionPerformed

    private void num14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num14ActionPerformed
        Troca(num14, num10);
        Troca(num14, num13);
        Troca(num14, num15);
        mensagem();
    }//GEN-LAST:event_num14ActionPerformed

    private void num15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num15ActionPerformed
         Troca(num15, num11);
         Troca(num15, num14);
         Troca(num15, vazio);
         mensagem();
    }//GEN-LAST:event_num15ActionPerformed

    private void vazioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vazioActionPerformed
         Troca(vazio, num12);
         Troca(vazio, num15);
         mensagem();
    }//GEN-LAST:event_vazioActionPerformed

    private void embarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_embarActionPerformed
        // TODO add your handling code here:
        embaralhar();
    }//GEN-LAST:event_embarActionPerformed

    private void soluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soluActionPerformed
        // TODO add your handling code here:
        solucao();
        mensagem();
    }//GEN-LAST:event_soluActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quebracbc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quebracbc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quebracbc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quebracbc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quebracbc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel clicks;
    private javax.swing.JLabel clique;
    private javax.swing.JButton embar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton num1;
    private javax.swing.JButton num10;
    private javax.swing.JButton num11;
    private javax.swing.JButton num12;
    private javax.swing.JButton num13;
    private javax.swing.JButton num14;
    private javax.swing.JButton num15;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JButton solu;
    private javax.swing.JButton vazio;
    // End of variables declaration//GEN-END:variables
}
